[package]
name = "peer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
webrtc = "0.8"
cpal = "0.15"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
log = "0.4"
env_logger = "0.9"

